on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:
name: main branch
jobs:
  run-base-cnb:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: '{{defaultContext}}:stacks/bionic/cnb/run'
          push: true
          tags: acmedotlimited/run:base-cnb
  run-tiny:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: '{{defaultContext}}:stacks/tiny/dockerfile/run'
          push: true
          tags: acmedotlimited/run:tiny
  run-tiny-cnb:
    needs: run-tiny
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: '{{defaultContext}}:stacks/tiny/cnb/run'
          push: true
          tags: acmedotlimited/run:tiny-cnb
